### ISSUE TITLE
Additional libraries get installed

### ISSUE THREAD

**Issue by handicraftsman** [glynos/url#1]
Your CMake project also installs gmock, gtest and tl into system.

**Comment by glynos** [comment]
Hello @handicraftsman 

I haven't worked on the install scripts for this library, they are still incomplete. Can you let me know exactly what you're trying to do so I can make a note of this?

**Comment by handicraftsman** [comment]
I was installing this library into a custom prefix (`~/Prefix`).

My configuration command was:
```bash
cmake .. -DCMAKE_INSTALL_PREFIX=/home/USERNAME/Prefix -DBUILD_SHARED_LIBS=ON
```

It also tried to use std::string_view which, of course, does not exist, but this should probably go to another issue.

**Comment by glynos** [comment]
What compiler/stdlib version are you using?
Also, I haven't tested using shared libraries yet. I'll look at this later this week.

**Comment by handicraftsman** [comment]
I am using GCC (G++) 7.3.0.

Regarding shared libraries:
* These additional libraries get installed in static mode too
* Looks like string_view problem is in headers.

By the way, inserting this snipped before including `skyr/url.hpp` helped me, although it's not the best solution:

```cpp
namespace std {
  using string_view = boost::string_view;
  using wstring_view = boost::wstring_view;
  using u16string_view = boost::u16string_view;
  using u32string_view = boost::u32string_view;
}
```

**Comment by handicraftsman** [comment]
Anywyas, nvm about string view - i did not notice that this project requires c++17.

**Comment by glynos** [comment]
Fixed: https://github.com/cpp-netlib/url/commit/590702320d80ab5e49e6487aee882440c57636cf
