### ISSUE TITLE
percent_encode ironically fails to encode percent

### ISSUE THREAD

**Issue by saurik** [glynos/url#15]
I might be crazy, and to be honest I'm using an old version of your library (as you keep using STL features that I just can't quite figure out how to get compiling for my targets... but I've read through the new code to try to verify the behavior and I'm not seeing this case now being handled), but it seems like skyr::percent_encode isn't encoding "%"/0x25?

**Comment by saurik** [comment]
I also am pretty sure that "+"/0x2b needs to be encoded, and that's not happening either. (I'm calling Amazon S3, and I have keys that contain all manner of awkward characters, and so I'm effectively participating in an percentage escape torture test ;P.)

**Comment by glynos** [comment]
What version are you using?

**Comment by saurik** [comment]
I am using 7c822cb; but, as stated, I also read the code at https://github.com/glynos/url/blob/515c6d3f27cabe9fdb6718da82927c3f019d899c/include/skyr/v1/percent_encoding/percent_encode.hpp and https://github.com/glynos/url/blob/515c6d3f27cabe9fdb6718da82927c3f019d899c/include/skyr/v1/percent_encoding/percent_encode_char.hpp -- which I would think is much more important than what I am using -- and I am not seeing any code that could possibly escape + or %: neither of these characters -- or their ordinals -- are present in any of the escape tables or are covered by any of the ranges.

**Comment by glynos** [comment]
Unless I miisunderstand what you're trying to do, this should fail for you:

```c++
  SECTION("encode_0x25") {
    auto encoded = skyr::percent_encoding::percent_encode_byte(
        std::byte(0x25), skyr::percent_encoding::encode_set::none);
    CHECK("%25" == encoded.to_string());
  }
```

Is that right?

**Comment by saurik** [comment]
So, I don't have that namespace in my version :(. ```skyr::percent_encode("%", skyr::encode_set::path)``` returns "%".

**Comment by glynos** [comment]
So I think I can reproduce your issue on the release you're using (v1.2). I think you want the following (which won't work for v1.2):

```c++

TEST(encode_tests, encode_0x25) {
  auto encoded = skyr::percent_encode_byte('\x25', skyr::encode_set::none);
  EXPECT_EQ("%25", encoded);
}
```

Although there is no "none" encode set, and with "path" the wrong behaviour is observed. This was an oversight at the time, but doing the equivalent using the current release does as expected (i.e. 0x2b and 0x25 are properly encoded).

If that's the case, I suggest you update to v1.13.0. However, there seems to be a reason you're sticking to v1.2.

**Comment by saurik** [comment]
OK, and I can confirm (I had the time to try the new version--not in my project, but just in a test case--and the API worked fine, though the behavior I actually wanted was in fact "path" ;P). I'm sorry about the obsolete non-issue. (FWIW, my core blocker on the new version of Skyr is that it uses parts of std::optional that are not available on my target, and I've yet to succeed in compiling in my own copy of libcxx on that one same specific platform as I get crashes in thread storage places. I'll probably have the time to fix it at some point.)

**Comment by saurik** [comment]
OK, I take it back: this issue stands, as I figured out how to do a true "path" encoding with the new APIs (I somehow thought you'd just removed the feature, but reading 9a670151ce4d46e6909fb0182ab49707fa7846fc made it more clear), and % isn't being encoded.

```
#include <iostream>
#include "skyr/v2/percent_encoding/percent_encode.hpp"

int main() {
    std::cout << skyr::percent_encode_bytes("%3F/?", skyr::percent_encoding::encode_set::path) << std::endl;
    return 0;
}
```

The result of this is "%3F/%3F", but I'd expect the answer to be "%253F/%3F": the / is valid inside of a path, the ? isn't (as it would delimit the query string), and (the key part) you can't ever not encode %, as it is used to encode other characters.

**Comment by glynos** [comment]
So I think I understand this better, and '%' is a legal character in a path (and query and fragment) according to the WhatWG spec (https://url.spec.whatwg.org/#percent-encoded-bytes)

By comparison, I tested using the Rust URL module (which also implements the WhatWG spec), and that does not encode the '%' character (see this Gist: https://gist.github.com/glynos/8a22fe8cf00837596542acaa69aa4a37)

**Comment by saurik** [comment]
While % is a legal character in a path, it is being handled there as some kind of fallback condition. Like, if you wanted to carefully attempt to not encode as many things as you can avoid encoding, you at least need to encode % any time it is followed by two hex characters: if you don't do this, and I have the string "%40" that I want to use as a path--as in I want the path that the server sees to be three characters long with a percent and two numbers instead of a single character "A"--I apparently have to not use the "encode percent for use as a path" function? The reason these variants want to exist is to allow for different behavior around bespoke disallowed characters (such as how ? is not allowed in a path or an anchor while clearly both being allowed in a URL, or how # isn't allowed in a path or a query), but they shouldn't make the underlying behavior of the function stop working correctly :(.
